# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 01:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20160521_2101'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
