# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-19 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20160619_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rotogrindersbatters',
            name='BABIP',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AlterField(
            model_name='rotogrindersbatters',
            name='BB',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AlterField(
            model_name='rotogrindersbatters',
            name='ISO',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AlterField(
            model_name='rotogrindersbatters',
            name='OBP',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AlterField(
            model_name='rotogrindersbatters',
            name='OPS',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AlterField(
            model_name='rotogrindersbatters',
            name='SLG',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AlterField(
            model_name='rotogrindersbatters',
            name='average',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AlterField(
            model_name='rotogrindersbatters',
            name='bats',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='rotogrindersbatters',
            name='ceiling',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='rotogrindersbatters',
            name='floor',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='rotogrindersbatters',
            name='kPercentage',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AlterField(
            model_name='rotogrindersbatters',
            name='name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='rotogrindersbatters',
            name='opponent',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='rotogrindersbatters',
            name='pitcherThrows',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='rotogrindersbatters',
            name='position',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='rotogrindersbatters',
            name='projPoints',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='rotogrindersbatters',
            name='salary',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='rotogrindersbatters',
            name='seasonAB',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AlterField(
            model_name='rotogrindersbatters',
            name='secondaryPosition',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='rotogrindersbatters',
            name='team',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='rotogrindersbatters',
            name='value',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='rotogrindersbatters',
            name='wOBA',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
