# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-10 04:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_swishanalyticspitchers'),
    ]

    operations = [
        migrations.CreateModel(
            name='PitcherLeftSplits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('team', models.CharField(blank=True, max_length=5, null=True)),
                ('opponent', models.CharField(blank=True, max_length=5, null=True)),
                ('ip', models.CharField(blank=True, max_length=7, null=True)),
                ('avg', models.CharField(blank=True, max_length=7, null=True)),
                ('woba', models.CharField(blank=True, max_length=7, null=True)),
                ('ops', models.CharField(blank=True, max_length=7, null=True)),
                ('knine', models.CharField(blank=True, max_length=7, null=True)),
                ('babip', models.CharField(blank=True, max_length=7, null=True)),
                ('bbPercentage', models.CharField(blank=True, max_length=7, null=True)),
                ('whip', models.CharField(blank=True, max_length=7, null=True)),
                ('era', models.CharField(blank=True, max_length=7, null=True)),
                ('fip', models.CharField(blank=True, max_length=7, null=True)),
                ('lob', models.CharField(blank=True, max_length=7, null=True)),
                ('fb', models.CharField(blank=True, max_length=7, null=True)),
                ('hrfb', models.CharField(blank=True, max_length=7, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PitcherLeftSplits', to='api.TimeKeeper')),
            ],
        ),
        migrations.CreateModel(
            name='PitcherRightSplits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('team', models.CharField(blank=True, max_length=5, null=True)),
                ('opponent', models.CharField(blank=True, max_length=5, null=True)),
                ('ip', models.CharField(blank=True, max_length=7, null=True)),
                ('avg', models.CharField(blank=True, max_length=7, null=True)),
                ('woba', models.CharField(blank=True, max_length=7, null=True)),
                ('ops', models.CharField(blank=True, max_length=7, null=True)),
                ('knine', models.CharField(blank=True, max_length=7, null=True)),
                ('babip', models.CharField(blank=True, max_length=7, null=True)),
                ('bbPercentage', models.CharField(blank=True, max_length=7, null=True)),
                ('whip', models.CharField(blank=True, max_length=7, null=True)),
                ('era', models.CharField(blank=True, max_length=7, null=True)),
                ('fip', models.CharField(blank=True, max_length=7, null=True)),
                ('lob', models.CharField(blank=True, max_length=7, null=True)),
                ('fb', models.CharField(blank=True, max_length=7, null=True)),
                ('hrfb', models.CharField(blank=True, max_length=7, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PitcherRightSplits', to='api.TimeKeeper')),
            ],
        ),
    ]
