# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-18 21:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rotowire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('bats', models.CharField(max_length=250)),
                ('position', models.CharField(max_length=250)),
                ('orderInLU', models.CharField(max_length=250)),
                ('opponent', models.CharField(max_length=250)),
                ('opponentThrows', models.CharField(max_length=250)),
                ('salary', models.CharField(max_length=250)),
                ('projPoints', models.CharField(max_length=250)),
                ('ceiling', models.CharField(max_length=250)),
                ('floor', models.CharField(max_length=250)),
                ('value', models.CharField(max_length=250)),
                ('moneyLine', models.CharField(max_length=250)),
                ('overUnder', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='TimeKeeper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('scraped', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='rotowire',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='api.TimeKeeper'),
        ),
    ]
