# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-19 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotowire',
            name='team',
            field=models.CharField(default='WSA', max_length=250),
        ),
    ]
